version: '3'

services:
  influxdb:
    image: influxdb:2
    env_file:
      - influxdb2.env
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdb2-data:/var/lib/influxdb2:rw
      - influxdb2-config:/etc/influxdb2
    ports:
      - "8086:8086"
  telegraf:
    image: telegraf:latest
    depends_on:
      - influxdb
    volumes:
      # Mount for telegraf config
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - influxdb2.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  influxdb2-data:
  influxdb2-config: